#!/bin/sh   
# test   
case $1 in  
    0)  
        synclient touchpadoff=0
        ;;  
    1)  
        synclient touchpadoff=1
        ;; 
    -h) 
    	echo -e "usage :\n\ttchctrl 0(open)/1(close)/-h(help)"
    	;; 
esac  